* Install basic tools and setup

** Add a new user when needed

#+BEGIN_SRC bash
  # Add new user
  useradd -m -G wheel YOUR_USER_NAME

  # Set password
  passwd YOUR_USER_NAME
#+END_SRC


** Install and configure =doas=

#+BEGIN_SRC bash
  pacman --sync --refresh opendoas
  
#+END_SRC


Then create =/etc/doas.conf= with the following settings:

#+BEGIN_SRC conf
  #
  # nopass   The user is not required to enter a password.
  # keepenv  Environment variables other than those listed in doas(1) are
  #          retained when creating the environment for the new process.
  #
  # Read `man doas.conf` for more details
  #
  permit nopass keepenv setenv { PATH } YOUR_USER_NAME as root
#+END_SRC

</br>

Make sure to change the file permission:

#+BEGIN_SRC bash
  chown -c root:root /etc/doas.conf
  chmod -c 0400 /etc/doas.conf
#+END_SRC


** Install everything I need

#+BEGIN_SRC bash
  doas pacman --sync --refresh tree git git-delta bat ripgrep procs htop btop fastfetch fzf fish lf neovim python-pynvim tmux emacs-nativecomp aspell aspell-en base-devel man-db man-pages

  #
  # Hyprland
  #
  doas pacman --sync --refresh hyprland xdg-desktop-portal-hyprland dunst qt6-wayland wl-clipboard alacritty tmux waybar mpv yt-dlp grim slurp nsxiv pavucontrol
#+END_SRC


** Change =fish= as default shell

#+BEGIN_SRC bash
  chsh -s /usr/bin/fish
#+END_SRC

Relogin to take effect.


** Create and copy GIT SSH key

#+BEGIN_SRC bash
  ssh-keygen -t ed25519 -C "YOUR_EMAIL_HERE"

  #
  # If you're using `Fish` shell, then better change to `bash` before you run
  # this command:
  #
  # bash
  #
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_ed25519

  #
  # Then ssh into this machine, cat the pub key and create SSH key on Github settings
  #
  cat ~/.ssh/id_ed25519.pub | wl-copy
#+END_SRC


** Setup git

#+BEGIN_SRC bash
  git config --global user.name "YOUR_PREFFERED_USER_NAME_HERE"
  git config --global user.email "YOUR_EMAIL_HERE"

  git config --global pull.rebase false
  git config --global core.pager delta
  git config --global interactive.diffFilter "delta --color-only"
  git config --global delta.navigate true
  git config --global delta.light false
  git config --global delta.line-numbers true
  git config --global delta.side-by-side true
  git config --global delta.show-syntax-themes true
  git config --global merge.conflictstyle diff3
  git config --global diff.colorMoved default
  git config --global init.defaultBranch master
#+END_SRC


** Install =Rust=, as =paru= needs it

#+BEGIN_SRC bash
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

  rustup component add rust-analyzer
#+END_SRC

Then relogin to take effects.


** Install =paru= - packages from =AUR (Arch User Repository)=

You have to install =sudo=, as =paru= uses it!!!

#+BEGIN_SRC bash
  # Switch to root
  su

  # Install sudo if not yet
  pacman --sync --refresh sudo

  # Allow `wheel` group to use `sudo`
  doas visudo
#+END_SRC


You need to install =rustup= first if not yet:

#+BEGIN_SRC bash
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#+END_SRC


Install =paru=:

#+BEGIN_SRC bash
  mkdir ~/temp && cd ~/temp

  sudo pacman -S --needed git base-devel
  git clone https://aur.archlinux.org/paru.git
  cd paru

  #
  # Choose '2', install `cargo` via `rustup` for a small download size!!!
  #
  makepkg -si

  #
  # If `makepkg -si` exit with error, then plz make sure to added the latest stable toolchain
  #
  rustup toolchain add stable

  #
  # Or if you've already install the stable toolchain, then update it
  #
  rustup update


  cd ~/temp && rm -rf paru
#+END_SRC



** Wallpaper related if you needed

#+BEGIN_SRC bash
  #
  # Wallpaper backend:
  #
  # Make sure to select =swww= (default =1=) rather than the =swww-git= (outdated)
  # and choose =rustup= (option =2=)!!!
  #
  paru --sync --refresh swww
#+END_SRC


*** Generate and change color-schemes on the fly by =pywal-16-colors=

#+BEGIN_SRC bash
  paru --sync --refresh pywal-16-colors
#+END_SRC


*** How to set wallpaper

#+BEGIN_SRC bash
  #
  # Init once
  #
  swww init

  #
  # Set wallpaper
  #
  swww img YOUR_WALLPAPER_FILENAME_HERE

  #
  # Apply transition when changing wallpaper
  #
  www img --transition-type wipe --transition-angle 45 YOUR_WALLPAPER_FILENAME_HERE
#+END_SRC


*** =waypaper= (GUI - frontend)

**** Install

#+BEGIN_SRC bash
  paru --sync --refresh waypaper
#+END_SRC


**** how to run

#+BEGIN_SRC bash
  #
  # Run with given backend, you only need to pass for the first time
  # and then 'waypaper' will keep using it
  #
  waypaper --backend swww
#+END_SRC

You might get the following error when choosing a wallpaper : =No such file or directory: swaybg=

That's you got a wrong settings in =~/.config/waypaper/config.ini=, open and fix it like below:

Pay attention to the =backend= setting!!!

#+BEGIN_SRC bash
  cat ~/.config/waypaper/config.ini

  # [Settings]
  # folder = /home/wison/Photos/wallpaper
  # fill = Fill
  # sort = name
  # backend = swww
  # color = #FFFFFF
  # language = en
  # subfolders = False
  # wallpaper = /home/wison/Photos/wallpaper/forest.jpg
  # monitors = All
#+END_SRC


**** In Hyperland configuration 

#+BEGIN_SRC bash
  #
  # Reset to the last chosen wallpaper
  #
  exec-once = waypaper --restore
#+END_SRC



** Generate dynamic colors from a given wallpaper

#+BEGIN_SRC bash
  doas pacman --sync --refresh pywal-16-colors
#+END_SRC

Then you can run =wal -i {FULLPATH_WALLPAPER_HERE}= to generate ~/.cache/wal~ folder that contains a lot of supported color templates.

You can add your own template files to =~/.config/wal/templates= folder to support what it's missing. Basically, you just need to add those ={colorX.strip}= templates in the correct syntax for your export target to set the special env vars.

For example, for =Hyprland= and =Fish=, you need to add the following template files to =~/.config/wal/templates=:

***  =~/.config/wal/templates/colors-hyprland.conf=

#+BEGIN_SRC conf
  $foreground = rgb({foreground.strip})
  $background = rgb({background.strip})
  $wallpaper = {wallpaper}

  $color0 = rgb({color0.strip})
  $color1 = rgb({color1.strip})
  $color2 = rgb({color2.strip})
  $color3 = rgb({color3.strip})
  $color4 = rgb({color4.strip})
  $color5 = rgb({color5.strip})
  $color6 = rgb({color6.strip})
  $color7 = rgb({color7.strip})
  $color8 = rgb({color8.strip})
  $color9 = rgb({color9.strip})
  $color10 = rgb({color10.strip})
  $color11 = rgb({color11.strip})
  $color12 = rgb({color12.strip})
  $color13 = rgb({color13.strip})
  $color14 = rgb({color14.strip})
  $color15 = rgb({color15.strip})
#+END_SRC


***  =~/.config/wal/templates/colors-fish.fish=

#+BEGIN_SRC conf
  set --export foreground {foreground.strip}
  set --export background {background.strip}
  set --export color0 {color0.strip}
  set --export color1 {color1.strip}
  set --export color2 {color2.strip}
  set --export color3 {color3.strip}
  set --export color4 {color4.strip}
  set --export color5 {color5.strip}
  set --export color6 {color6.strip}
  set --export color7 {color7.strip}
  set --export color8 {color8.strip}
  set --export color9 {color9.strip}
  set --export color10 {color10.strip}
  set --export color11 {color11.strip}
  set --export color12 {color12.strip}
  set --export color13 {color13.strip}
  set --export color14 {color14.strip}
  set --export color15 {color15.strip}
#+END_SRC


*** Handy script to pick a wallpaper randomly and call =wal -i= to generate the corresponding colors

Here is my =~/.config/waybar/scripts/random_wallpaper_update_colors.sh=:

#+BEGIN_SRC bash
  #!/usr/bin/fish

  set wallpaper_folder $argv[1]

  #
  # `if` help:  https://fishshell.com/docs/current/language.html#the-if-statement
  # `test` help: https://fishshell.com/docs/current/cmds/test.html
  #
  if test -z $wallpaper_folder
     echo "Usage: change_wallpaper.sh [wallpaper_folder]"
     exit 0
  end

  set random_file (ls $wallpaper_folder |sort -R |tail -n1)
  set fullpath_wallpaper "$wallpaper_folder$random_file"
  echo "wallpaper_folder: $wallpaper_folder"
  echo "random_file: $random_file"
  echo "fullpath_wallpaper: $fullpath_wallpaper"

  swww img --transition-type none $fullpath_wallpaper && wal -i $fullpath_wallpaper
  pkill waybar
  # sleep 1
  dbus-run-session waybar > ~/.waybar.log
#+END_SRC

It accepts a fullpath image filename to set as wallpaper and call =wal= to generate corresponding colors and reload =waybar=.


** Cava: Console-based Audio Visualizer for Alsa

#+BEGIN_SRC bash
  paru --sync --refresh cava
#+END_SRC


If you want waybar support, then you have to remove the installed =waybar=, as the package version doesn't support =cava= module. You need to install the supported version by =paru=:

#+BEGIN_SRC bash
  doas pacman -Rsun waybar

  paru --sync --refresh waybar-cava
#+END_SRC


After that, enable the "cava" module in your =~/.config/waybar/config=.


** Vim-liked keybindings document (PDF) viewer: 

#+BEGIN_SRC bash
  doas pacman --sync --refresh zathura zathura-pdf-poppler

  #
  # Create a symbol link
  #
  doas ln -s /usr/bin/zathura /usr/bin/pdfviewer
#+END_SRC

Then, run =pdfviewer YOUR_PDF_FILE=


Keybindings

| Keybindings     | Description                      |
|-----------------+----------------------------------|
| [Open and quit] |                                  |
| =q=               | Quit                             |
| =:open=           | Open                             |
| [Navigation]    |                                  |
| =J/space=         | Next page                        |
| =K=               | Prev page                        |
| =j=               | Move down                        |
| =k=               | Move up                          |
| =C-d=             | Page down                        |
| =C-u=             | Page up                          |
| =gg=              | Go to first page                 |
| =G=               | Go to last page                  |
| =Xgg=             | Go to page X, =10gg= go to page 10 |
| [Fit window]    |                                  |
| =a=               | Fit with window height           |
| =s=               | Fit with window width            |
| =d=               | Toggle double-page mode          |
| [Zoom]          |                                  |
| =-=               | Zoom-out                         |
| =+=               | Zoom-in                          |
| =               | Overview all pages               |
| [Rotation]      |                                  |
| =r=               | Rotate the page                  |
| [Search]        |                                  |
| /               | Search                           |


** Run =Hyprland=

You should make sure that the following services are running:

#+BEGIN_SRC bash
  systemctl --user status pipewire wireplumber 
#+END_SRC

Otherwise, enbable it before starting =Hyprland=.

#+BEGIN_SRC bash
  Hyprland
#+END_SRC



Also, =xdg-desktop-portal-hyprland= should start automatically:

#+BEGIN_SRC bash
  procs desktop

  # PID:▲ User  │ TTY CPU MEM CPU Time │ Command
  #             │     [%] [%]          │
  # 923   wison │     0.0 0.0 00:00:00 │ /usr/lib/xdg-desktop-portal
  # 951   wison │     0.0 0.1 00:00:00 │ /usr/lib/xdg-desktop-portal-hyprland
  # 1339  wison │     0.0 0.0 00:00:00 │ /usr/lib/xdg-desktop-portal
  # 1370  wison │     0.0 0.1 00:00:00 │ /usr/lib/xdg-desktop-portal-hyprland
#+END_SRC

Have a look at here to know more about =xdg-desktop-portal-hyprland (XDPH)=:
https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/


** Install nerd font

=Nerd Fonts= is a project that patches developer targeted fonts with a high number of glyphs (icons). Basically, it adds all popular icons into the popular fonts which call `patched font` which include the original font and all supported icons. Then you can use any of those `patched font` to show any supported icons below:

*** Installation

It has 7 optional ways to install =Nerd Fonts=. But for =Arch=, you can install via =AUR=. Let's take the =Source Code Pro= at an example:

#+BEGIN_SRC bash
  paru -S nerd-fonts-source-code-pro

  # If you use new version Arch Linux, use this as a replcement
  paru -S ttf-sourcecodepro-nerd
#+END_SRC


After installing, you can run the command below to show the installed location:

#+BEGIN_SRC bash
  paru --query --list nerd-fonts-source-code-pro

  # If you use new version Arch Linux, use this as a replcement
  paru --query --list ttf-sourcecodepro-nerd

  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete.ttf
#+END_SRC


*** Setup correct font name

As you can see that, the font name is NOT the =Source Code Pro=!!! So you have to run the command below to know the =Real font name= which you can fill into any application's font configuration file:

#+BEGIN_SRC bash
  fc-list | grep Pro

  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Light Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Black Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Semibold,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Bold
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Semibold Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Light,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Bold
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Medium Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Medium,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=ExtraLight Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Bold Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Medium Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Light,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Bold Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=ExtraLight,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Black,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Black Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=ExtraLight,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Medium,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Black,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Semibold Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=ExtraLight Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Semibold,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Light Italic,Italic
#+END_SRC

Right now, you should notice that the font name is either =SauceCodePro Nerd Font Mono= or =SauceCodePro Nerd Font=. So fill them into your application font configuration file.

For example, put it into the =Alacritty= configuration file:

#+BEGIN_SRC conf
  # Bold italic font face
  bold_italic:

  # Font family
  #
  # If the bold italic family is not specified, it will fall back to the
  # value specified for the normal font.
  family: "SauceCodePro Nerd Font"

  # The `style` can be specified to pick a specific face.
  style: Bold Italic
#+END_SRC


*** Copy icons from =NerdFont= cheatsheet

After setting the correct font name, then you can copy and paste the icons from the [[https://www.nerdfonts.com/cheat-shee][NerdFont cheatsheet]] :


Just type any searching keyword there, place the mouse on top of the one you like, it will show up a popup menu on the right-top corner. So, click =Icon= to copy to clipbobard, then you can paste to anywhere to have that icon.


*** =Vim= support

Add the settings below to your =vimrc= or =init.vim= (for =neovim=):

#+BEGIN_SRC bash
  # 
  Plug 'ryanoasis/vim-devicons'

  # Set the `guifont` to your patched font name with the size
  set guifont=SauceCodePro\ Nerd\ Font\ 11

  # Enable this line if you use `vim-airline`
  let g:airline_powerline_fonts = 1
#+END_SRC

Then run =:PlugInstall= and restart `vim` to take effect.


** Bluetooth

*** Install

#+BEGIN_SRC bash
  doas pacman --sync --refresh bluez bluez-utils
#+END_SRC


*** Enable and start service

#+BEGIN_SRC bash
  doas systemctl enable bluetooth.service
  doas systemctl restart bluetooth.service
  systemctl status bluetooth.service
#+END_SRC


*** Make sure =rfkill= not block your bluetooth adapter

=rfkill= a tool for enabling and disabling wireless device.

#+BEGIN_SRC bash
  doas rfkill list

  # 0: hci0: Bluetooth
  #         Soft blocked: no
  #         Hard blocked: no
  # 1: tpacpi_bluetooth_sw: Bluetooth
  #         Soft blocked: no
  #         Hard blocked: no
  # 2: phy0: Wireless LAN
  #         Soft blocked: no
  #         Hard blocked: no
#+END_SRC

The case above means no block at all, that's fine. If you see it's blocked, then run the command below to unblock:

#+BEGIN_SRC bash
  doas rfkill unblock bluetooth
#+END_SRC


*** Scan, pair, connect and trust device

First, turn off your bluetooth device which want to connect to.

Run =bluetoothctl=, then follow the steps below to connect:

#+BEGIN_SRC bash
  #
  # Make sure turn on the bluetooth
  #
  power on

  #
  # Enable scan, after that, bluetooth devices show up there one by one
  #
  scan on

  #
  # Right now, turn on your bluetooth device, then wait for it to show up.
  # Hopefully, it shows its name directly which you can confirm that's your device.
  # If it doesn't, only show the MAC ID, then copy that Id and run the
  # command to confirm.
  #
  info XX:XX:XX:XX:XX:XX

  #
  # Once you confirm that your device, then do:
  #
  pair XX:XX:XX:XX:XX:XX

  #
  # After pairing, you can connect to it
  #
  connect XX:XX:XX:XX:XX:XX

  #
  # Optionally, you can trust it and it will auto connect next time
  #
  trust XX:XX:XX:XX:XX:XX

  #
  # Quit
  #
  quit
#+END_SRC


Here is the full example:

#+BEGIN_SRC bash
  #
  # Power on and scan on
  #
  [bluetooth]# Agent registered
  [bluetooth]# [CHG] Controller 50:76:AF:45:E1:BE Pairable: yes
  [bluetooth]# power on
  [bluetooth]# Changing power on succeeded
  [bluetooth]# scan on
  [bluetooth]# SetDiscoveryFilter success
  [bluetooth]# Discovery started

  #
  # Start showing scanned devices
  #
  [bluetooth]# [CHG] Controller 50:76:AF:45:E1:BE Discovering: yes
  [bluetooth]# [NEW] Device 5A:5D:6C:AA:14:90 5A-5D-6C-AA-14-90
  [bluetooth]# [NEW] Device 67:FD:70:A2:5A:FF Cellar TV
  [bluetooth]# [NEW] Device 60:21:AA:4E:F4:63 60-21-AA-4E-F4-63

  #
  # See my JBL headphone
  #
  [bluetooth]# [NEW] Device 84:D3:52:AD:CF:4F JBL TOUR ONE M2

  #
  # Pair
  #
  pair 84:D3:52:AD:CF:4F
  Attempting to pair with 84:D3:52:AD:CF:4F
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F Bonded: yes
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F Modalias: bluetooth:v02B0p0000d001F
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F ServicesResolved: yes
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F Paired: yes
  [JBL TOUR ONE M2]# Pairing successful
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F ServicesResolved: no
  [CHG] Device 84:D3:52:AD:CF:4F Connected: no

  #
  # Connect to it after pairing
  #
  connect 84:D3:52:AD:CF:4F
  Attempting to connect to 84:D3:52:AD:CF:4F
  [CHG] Device 84:D3:52:AD:CF:4F Connected: yes
  [JBL TOUR ONE M2]# [NEW] Endpoint /org/bluez/hci0/dev_84_D3_52_AD_CF_4F/sep1
  [JBL TOUR ONE M2]# [NEW] Endpoint /org/bluez/hci0/dev_84_D3_52_AD_CF_4F/sep2
  [JBL TOUR ONE M2]# [NEW] Transport /org/bluez/hci0/dev_84_D3_52_AD_CF_4F/sep2/fd0
  [JBL TOUR ONE M2]# [CHG] Transport /org/bluez/hci0/dev_84_D3_52_AD_CF_4F/sep2/fd0 Delay: 0x05dc (1500)
  [JBL TOUR ONE M2]# Connection successful
  [JBL TOUR ONE M2]# [CHG] Transport /org/bluez/hci0/dev_84_D3_52_AD_CF_4F/sep2/fd0 Volume: 0x004f (79)
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F ServicesResolved: yes

  #
  # Trust it after connecting
  #
  [JBL T84:D3:52:AD:CF:4Ft 84:D3:52:AD:CF:4F
  [JBL TOUR ONE M2]# [CHG] Device 84:D3:52:AD:CF:4F Trusted: yes
  [JBL TOUR ONE M2]# Changing 84:D3:52:AD:CF:4F trust succeeded

  #
  # Exit
  #
  quit
#+END_SRC


*** =bluetoothctl= usage

**** List aviablable devices (your onboard bluetooth chipset)

#+BEGIN_SRC bash
  bluetoothctl list
  # Controller 50:76:AF:45:E1:BE my-arch [default]
#+END_SRC


**** List all (Paired/Connected/Trusted) deivces

#+BEGIN_SRC bash
  bluetoothctl devices
  # Device 84:D3:52:AD:CF:4F JBL TOUR ONE M2

  #
  # Or you can list devices with filter condition: Trusted/Paired/Connected
  #
  bluetoothctl devices Paired
  # Device 84:D3:52:AD:CF:4F JBL TOUR ONE M2
#+END_SRC


*** Connect trusted device by script

Create =~/connect-bluetooth.sh= with the following content:

#+BEGIN_SRC bash
  #!/bin/sh
  bluetoothctl -- power on
  bluetoothctl -- connect 84:D3:52:AD:CF:4F
#+END_SRC


** Install =Brave= browser

#+BEGIN_SRC bash
  paru --sync --refresh brave-bin
#+END_SRC

Open =brave= and open URL =brave://flags=, then search for =ozone=, choose =wayland= in the dropdown menu.


** Install chinese fonts

#+BEGIN_SRC bash
  paru --sync --refresh adobe-source-han-mono-cn-fonts \
    adobe-source-han-sans-cn-fonts \
    adobe-source-han-serif-cn-fonts
#+END_SRC
