* Install basic tools and setup

** Add a new user when needed

#+BEGIN_SRC bash
  # Add new user
  useradd -m -G wheel YOUR_USER_NAME

  # Set password
  passwd YOUR_USER_NAME
#+END_SRC


** Install and configure =doas=

#+BEGIN_SRC bash
  pacman --sync --refresh opendoas
  
#+END_SRC


Then create =/etc/doas.conf= with the following settings:

#+BEGIN_SRC conf
  #
  # nopass   The user is not required to enter a password.
  # keepenv  Environment variables other than those listed in doas(1) are
  #          retained when creating the environment for the new process.
  #
  # Read `man doas.conf` for more details
  #
  permit nopass keepenv setenv { PATH } YOUR_USER_NAME as root
#+END_SRC

</br>

Make sure to change the file permission:

#+BEGIN_SRC bash
  chown -c root:root /etc/doas.conf
  chmod -c 0400 /etc/doas.conf
#+END_SRC


** Install everything I need

#+BEGIN_SRC bash
  doas pacman --sync --refresh tree git git-delta bat ripgrep procs htop btop fastfetch fzf fish lf neovim python-pynvim tmux emacs-nativecomp aspell aspell-en base-devel man-db man-pages

  #
  # Hyprland
  #
  doas pacman --sync --refresh hyprland xdg-desktop-portal-hyprland dunst qt6-wayland wl-clipboard alacritty tmux waybar mpv yt-dlp grim slurp nsxiv pavucontrol
#+END_SRC


** Change =fish= as default shell

#+BEGIN_SRC bash
  chsh -s /usr/bin/fish
#+END_SRC

Relogin to take effect.


** Create and copy GIT SSH key

#+BEGIN_SRC bash
  ssh-keygen -t ed25519 -C "YOUR_EMAIL_HERE"

  #
  # If you're using `Fish` shell, then better change to `bash` before you run
  # this command:
  #
  # bash
  #
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_ed25519

  #
  # Then ssh into this machine, cat the pub key and create SSH key on Github settings
  #
  cat ~/.ssh/id_ed25519.pub | wl-copy
#+END_SRC


** Setup git

#+BEGIN_SRC bash
  git config --global user.name "YOUR_PREFFERED_USER_NAME_HERE"
  git config --global user.email "YOUR_EMAIL_HERE"

  git config --global pull.rebase false
  git config --global core.pager delta
  git config --global interactive.diffFilter "delta --color-only"
  git config --global delta.navigate true
  git config --global delta.light false
  git config --global delta.line-numbers true
  git config --global delta.side-by-side true
  git config --global delta.show-syntax-themes true
  git config --global merge.conflictstyle diff3
  git config --global diff.colorMoved default
  git config --global init.defaultBranch master
#+END_SRC


** Install =Rust=, as =paru= needs it

#+BEGIN_SRC bash
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

  rustup component add rust-analyzer
#+END_SRC

Then relogin to take effects.


** Install =paru= - packages from =AUR (Arch User Repository)=

You have to install =sudo=, as =paru= uses it!!!

#+BEGIN_SRC bash
  # Switch to root
  su

  # Install sudo if not yet
  pacman --sync --refresh sudo

  # Allow `wheel` group to use `sudo`
  doas visudo
#+END_SRC


You need to install =rustup= first if not yet:

#+BEGIN_SRC bash
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#+END_SRC


Install =paru=:

#+BEGIN_SRC bash
  mkdir ~/temp && cd ~/temp

  sudo pacman -S --needed git base-devel
  git clone https://aur.archlinux.org/paru.git
  cd paru

  #
  # Choose '2', install `cargo` via `rustup` for a small download size!!!
  #
  makepkg -si

  #
  # If `makepkg -si` exit with error, then plz make sure to added the latest stable toolchain
  #
  rustup toolchain add stable

  #
  # Or if you've already install the stable toolchain, then update it
  #
  rustup update


  cd ~/temp && rm -rf paru
#+END_SRC



** Wallpaper related if you needed

#+BEGIN_SRC bash
  #
  # Wallpaper backend:
  #
  # Make sure to select =swww= (default =1=) rather than the =swww-git= (outdated)
  # and choose =rustup= (option =2=)!!!
  #
  paru --sync --refresh swww
#+END_SRC


*** How to set wallpaper

#+BEGIN_SRC bash
  #
  # Init once
  #
  swww init

  #
  # Set wallpaper
  #
  swww img YOUR_WALLPAPER_FILENAME_HERE

  #
  # Apply transition when changing wallpaper
  #
  www img --transition-type wipe --transition-angle 45 YOUR_WALLPAPER_FILENAME_HERE
#+END_SRC


*** =waypaper= (GUI - frontend)

**** Install

#+BEGIN_SRC bash
  paru --sync --refresh waypaper
#+END_SRC


**** how to run

#+BEGIN_SRC bash
  #
  # Run with given backend, you only need to pass for the first time
  # and then 'waypaper' will keep using it
  #
  waypaper --backend swww
#+END_SRC

You might get the following error when choosing a wallpaper : =No such file or directory: swaybg=

That's you got a wrong settings in =~/.config/waypaper/config.ini=, open and fix it like below:

Pay attention to the =backend= setting!!!

#+BEGIN_SRC bash
  cat ~/.config/waypaper/config.ini

  # [Settings]
  # folder = /home/wison/Photos/wallpaper
  # fill = Fill
  # sort = name
  # backend = swww
  # color = #FFFFFF
  # language = en
  # subfolders = False
  # wallpaper = /home/wison/Photos/wallpaper/forest.jpg
  # monitors = All
#+END_SRC


**** In Hyperland configuration 

#+BEGIN_SRC bash
  #
  # Reset to the last chosen wallpaper
  #
  exec-once = waypaper --restore
#+END_SRC



** Cava: Console-based Audio Visualizer for Alsa

#+BEGIN_SRC bash
  paru --sync --refresh cava
#+END_SRC


If you want waybar support, then you have to remove the installed =waybar=, as the package version doesn't support =cava= module. You need to install the supported version by =paru=:

#+BEGIN_SRC bash
  doas pacman -Rsun waybar

  paru --sync --refresh waybar-cava
#+END_SRC


After that, enable the "cava" module in your =~/.config/waybar/config=.


** Run =Hyprland=

You should make sure that the following services are running:

#+BEGIN_SRC bash
  systemctl --user status pipewire wireplumber 
#+END_SRC

Otherwise, enbable it before starting =Hyprland=.

#+BEGIN_SRC bash
  Hyprland
#+END_SRC



Also, =xdg-desktop-portal-hyprland= should start automatically:

#+BEGIN_SRC bash
  procs desktop

  # PID:▲ User  │ TTY CPU MEM CPU Time │ Command
  #             │     [%] [%]          │
  # 923   wison │     0.0 0.0 00:00:00 │ /usr/lib/xdg-desktop-portal
  # 951   wison │     0.0 0.1 00:00:00 │ /usr/lib/xdg-desktop-portal-hyprland
  # 1339  wison │     0.0 0.0 00:00:00 │ /usr/lib/xdg-desktop-portal
  # 1370  wison │     0.0 0.1 00:00:00 │ /usr/lib/xdg-desktop-portal-hyprland
#+END_SRC

Have a look at here to know more about =xdg-desktop-portal-hyprland (XDPH)=:
https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/


** Install nerd font

=Nerd Fonts= is a project that patches developer targeted fonts with a high number of glyphs (icons). Basically, it adds all popular icons into the popular fonts which call `patched font` which include the original font and all supported icons. Then you can use any of those `patched font` to show any supported icons below:

*** Installation

It has 7 optional ways to install =Nerd Fonts=. But for =Arch=, you can install via =AUR=. Let's take the =Source Code Pro= at an example:

#+BEGIN_SRC bash
  paru -S nerd-fonts-source-code-pro

  # If you use new version Arch Linux, use this as a replcement
  paru -S ttf-sourcecodepro-nerd
#+END_SRC


After installing, you can run the command below to show the installed location:

#+BEGIN_SRC bash
  paru --query --list nerd-fonts-source-code-pro

  # If you use new version Arch Linux, use this as a replcement
  paru --query --list ttf-sourcecodepro-nerd

  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete Mono.ttf
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete.ttf
#+END_SRC


*** Setup correct font name

As you can see that, the font name is NOT the =Source Code Pro=!!! So you have to run the command below to know the =Real font name= which you can fill into any application's font configuration file:

#+BEGIN_SRC bash
  fc-list | grep Pro

  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Light Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Black Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Semibold,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Bold
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Semibold Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Light,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Bold
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Medium Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Medium,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=ExtraLight Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Bold Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Medium Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Light Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Light,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Bold Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Bold Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=ExtraLight,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Black,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Black Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=ExtraLight,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Medium Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Medium,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Black Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Black,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Semibold Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro ExtraLight Italic Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=ExtraLight Italic,Italic
  # /usr/share/fonts/TTF/Sauce Code Pro Nerd Font Complete Mono.ttf: SauceCodePro Nerd Font Mono:style=Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Semibold Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Semibold,Regular
  # /usr/share/fonts/TTF/Sauce Code Pro Light Italic Nerd Font Complete.ttf: SauceCodePro Nerd Font:style=Light Italic,Italic
#+END_SRC

Right now, you should notice that the font name is either =SauceCodePro Nerd Font Mono= or =SauceCodePro Nerd Font=. So fill them into your application font configuration file.

For example, put it into the =Alacritty= configuration file:

#+BEGIN_SRC conf
  # Bold italic font face
  bold_italic:

  # Font family
  #
  # If the bold italic family is not specified, it will fall back to the
  # value specified for the normal font.
  family: "SauceCodePro Nerd Font"

  # The `style` can be specified to pick a specific face.
  style: Bold Italic
#+END_SRC


*** Copy icons from =NerdFont= cheatsheet

After setting the correct font name, then you can copy and paste the icons from the [[https://www.nerdfonts.com/cheat-shee][NerdFont cheatsheet]] :


Just type any searching keyword there, place the mouse on top of the one you like, it will show up a popup menu on the right-top corner. So, click =Icon= to copy to clipbobard, then you can paste to anywhere to have that icon.


*** =Vim= support

Add the settings below to your =vimrc= or =init.vim= (for =neovim=):

#+BEGIN_SRC bash
  # 
  Plug 'ryanoasis/vim-devicons'

  # Set the `guifont` to your patched font name with the size
  set guifont=SauceCodePro\ Nerd\ Font\ 11

  # Enable this line if you use `vim-airline`
  let g:airline_powerline_fonts = 1
#+END_SRC

Then run =:PlugInstall= and restart `vim` to take effect.
